{% set version = "1.13.0" %}
{% set sha256 = "700605fe0034d4e0a93e3a7316910300134d0bd8ee652dcafc28a6f3a313223c" %}

{% set build = 0 %}

package:
  name: qpoint
  version: {{ version }}

source:
  url: https://github.com/arahlin/qpoint/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]
  script_env:
    - QPOINT_VERSION={{ version }}

requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp # [osx]
  host:
    - llvm-openmp # [osx]
    - libgomp # [linux]
    - libopenblas * *openmp*
    - libblas * *openblas
    - python
    - setuptools
    - extension-helpers
    - setuptools-scm
    - numpy
    - scipy
    # Although not a dependency, we put numba here to force
    # building with a numba-compatible numpy version
    - numba
    # Adding astropy as a host dependency will download the current
    # IERS data and store it in the package
    - astropy
  run:
    - llvm-openmp # [osx]
    - libopenblas * *openmp*
    - libblas * *openblas
    - {{ pin_compatible("scipy") }}
    - {{ pin_compatible("libopenblas") }}
    - {{ pin_compatible("libblas") }}
    - python
    - astropy

test:
  imports:
    - qpoint

about:
  home: https://github.com/arahlin/qpoint
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Quaternion library for telescope pointing
  description: |
    A lightweight quaternion-based library for telescope pointing
  dev_url: https://github.com/arahlin/qpoint

extra:
  recipe-maintainers:
    - tskisner
