{% set version = "0.2.5" %}
{% set sha256 = "d2721ce5d6e4b1726ee32bec849001ee1c41149462c56b4cb01c330568db0493" %}

{% set build = 0 %}

package:
  name: so3g
  version: {{ version }}

source:
  url: https://github.com/simonsobs/so3g/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - llvm-openmp # [osx]
  host:
    - llvm-openmp # [osx]
    - libgomp # [linux]
    - libopenblas * *openmp*
    - libblas * *openblas
    - openblas * *openmp*
    - python
    - numpy
    - scipy
    - boost
    - libboost-devel
    - libboost-python-devel
    - libflac
    - gsl
    - glog
    - ceres-solver=*=cpu*
    - qpoint
    # Although not a dependency, we put numba here to force
    # building with a numba-compatible numpy version
    - numba
    # Not a dependency, force installing a NaMaster-compatible GSL version
    - namaster >=2.4
  run:
    - llvm-openmp # [osx]
    - libopenblas * *openmp*
    - libblas * *openblas
    - {{ pin_compatible("scipy") }}
    - {{ pin_compatible("libopenblas") }}
    - {{ pin_compatible("libblas") }}
    - {{ pin_compatible("libboost-python") }}
    - {{ pin_compatible("libboost") }}
    - {{ pin_compatible("libflac") }}
    - {{ pin_compatible("gsl") }}
    - python
    - astropy
    - qpoint
    - matplotlib
    - ephem
    - pytz
    - pyaml
    - sqlalchemy
    - pysqlite3
    - tqdm
    - ceres-solver=*=cpu*

test:
  imports:
    - so3g

about:
  home: https://github.com/simonsobs/so3g
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simons Observatory SPT3G Tools
  description: |
    Glue functions and new classes for SO work in the spt3g paradigm.
  dev_url: https://github.com/simonsobs/so3g

extra:
  recipe-maintainers:
    - tskisner
