{% set version = "0.29.0" %}
{% set sha256 = "b08b81b6df62dc01a8b8ed639a6fa593963b7593dbb9638f483fca78930a658f" %}

{% set build = 0 %}

package:
  name: pixell
  version: {{ version }}

source:
  url: https://github.com/simonsobs/pixell/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - llvm-openmp # [osx]
    - automake
    - autoconf
    - m4
    - libtool
    - make
  host:
    - llvm-openmp # [osx]
    - libgomp # [linux]
    - libopenblas * *openmp*
    - libblas * *openblas
    - python
    - meson-python
    - cython
    - numpy
    - scipy
    - astropy
    - healpy
    - matplotlib
    - pyyaml
    - h5py
    - pillow
    - pyfftw
    # Remove until this perl bug is fixed
    # https://github.com/conda-forge/perl-feedstock/issues/56
    - libxcrypt1   # [linux]
  run:
    - llvm-openmp # [osx]
    - libopenblas * *openmp*
    - libblas * *openblas
    - {{ pin_compatible("scipy") }}
    - {{ pin_compatible("libopenblas") }}
    - {{ pin_compatible("libblas") }}
    - python
    - astropy
    - healpy
    - matplotlib
    - pyyaml
    - h5py
    - pillow
    - pyfftw

test:
  imports:
    - pixell

about:
  home: https://github.com/simonsobs/pixell
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools for working with maps in rectangular pixelization.
  description: |
    Library for loading, manipulating and analyzing maps stored
    in rectangular pixelization.
  dev_url: https://github.com/simonsobs/pixell

extra:
  recipe-maintainers:
    - tskisner
