{% set version = "0.30.2" %}
{% set sha256 = "2ac8bd1d4574d6321f90ffd0a83a1a496066171143c95c0b9f32d1b761be2972" %}

{% set build = 0 %}

package:
  name: pixell
  version: {{ version }}

source:
  url: https://github.com/simonsobs/pixell/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - llvm-openmp # [osx]
    - automake
    - autoconf
    - m4
    - libtool
    - make
  host:
    - llvm-openmp # [osx]
    - libgomp # [linux]
    - libopenblas * *openmp* # [linux]
    - libopenblas # [osx]
    - libblas * *openblas
    - python
    - meson-python
    - cython
    - numpy
    - scipy
    - astropy
    - healpy
    - matplotlib
    - pyyaml
    - h5py
    - pillow
    - pyfftw
  run:
    - llvm-openmp # [osx]
    - libopenblas * *openmp* # [linux]
    - libopenblas # [osx]
    - libblas * *openblas
    - {{ pin_compatible("scipy") }}
    - {{ pin_compatible("libopenblas") }}
    - {{ pin_compatible("libblas") }}
    - python
    - astropy
    - healpy
    - matplotlib
    - pyyaml
    - h5py
    - pillow
    - pyfftw

test:
  imports:
    - pixell

about:
  home: https://github.com/simonsobs/pixell
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools for working with maps in rectangular pixelization.
  description: |
    Library for loading, manipulating and analyzing maps stored
    in rectangular pixelization.
  dev_url: https://github.com/simonsobs/pixell

extra:
  recipe-maintainers:
    - tskisner
