{% set version = "0.19.2" %}
{% set sha256 = "aecc1bf6b2c6685d4641e76bdce40a4e4ed337cdffad69c294a9186ab8a5f9a1" %}

{% set build = 0 %}

package:
  name: pixell
  version: {{ version }}

source:
  url: https://github.com/simonsobs/pixell/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - openblas * openmp_*
    - libopenblas * openmp_*
    - libblas * *openblas
    - liblapack * *openblas
    - automake
    - autoconf
    - m4
    - libtool
    - python
    - cython
    - scipy
    - astropy
    - healpy
    - matplotlib
    - pyyaml
    - h5py
    - pillow
    # Revert to 0.12 until this bug is fixed:
    # https://github.com/conda-forge/pyfftw-feedstock/issues/51
    - pyfftw==0.12
    # Remove until this perl bug is fixed
    # https://github.com/conda-forge/perl-feedstock/issues/56
    - libxcrypt1   # [linux]
  run:
    - openblas * openmp_*
    - libopenblas * openmp_*
    - libblas * *openblas
    - liblapack * *openblas
    - python
    - numpy
    - scipy
    - astropy
    - healpy
    - matplotlib
    - pyyaml
    - h5py
    - pillow
    - pyfftw==0.12

test:
  imports:
    - pixell

about:
  home: https://github.com/simonsobs/pixell
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools for working with maps in rectangular pixelization.
  description: |
    Library for loading, manipulating and analyzing maps stored
    in rectangular pixelization.
  dev_url: https://github.com/simonsobs/pixell

extra:
  recipe-maintainers:
    - tskisner
